services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - "./localstack_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SERVICES=s3,sns
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
  
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - redis_cache:/data

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: dhwani_frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"

  # backend:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   container_name: dhwani_backend
  #   restart: always
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - postgres
  #     - redis
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
  #     - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  redis_cache:
